runtime: nodejs22
automatic_scaling:
  max_instances: 1
env_variables:
  WIDGET_DIR: widget
handlers:
  - url: /favicon\.png
    static_files: public/favicon.png
    upload: public/favicon\.png
  - url: /static
    static_dir: public
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto